//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AtributeResourses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AtributeResourses() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AtributeResourses", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Номер квартиры.
        /// </summary>
        internal static string Address_Flat {
            get {
                return ResourceManager.GetString("Address_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дом.
        /// </summary>
        internal static string Address_House {
            get {
                return ResourceManager.GetString("Address_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Название.
        /// </summary>
        internal static string City_Name {
            get {
                return ResourceManager.GetString("City_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Название.
        /// </summary>
        internal static string Company_CompanyName {
            get {
                return ResourceManager.GetString("Company_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как ИНН.
        /// </summary>
        internal static string Company_INN {
            get {
                return ResourceManager.GetString("Company_INN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как ФИО.
        /// </summary>
        internal static string Customer_FIO {
            get {
                return ResourceManager.GetString("Customer_FIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Номер паспорта.
        /// </summary>
        internal static string Customer_Passport {
            get {
                return ResourceManager.GetString("Customer_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Номер телефона.
        /// </summary>
        internal static string Customer_PhoneNumber {
            get {
                return ResourceManager.GetString("Customer_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Номер.
        /// </summary>
        internal static string House_Number {
            get {
                return ResourceManager.GetString("House_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Улица.
        /// </summary>
        internal static string House_Street {
            get {
                return ResourceManager.GetString("House_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Название.
        /// </summary>
        internal static string MeterType_Name {
            get {
                return ResourceManager.GetString("MeterType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Тип.
        /// </summary>
        internal static string Meter_MeterType {
            get {
                return ResourceManager.GetString("Meter_MeterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Название.
        /// </summary>
        internal static string Meter_Name {
            get {
                return ResourceManager.GetString("Meter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дата выполнения заказа.
        /// </summary>
        internal static string OrderEntry_EndTime {
            get {
                return ResourceManager.GetString("OrderEntry_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Счётчик.
        /// </summary>
        internal static string OrderEntry_Meter {
            get {
                return ResourceManager.GetString("OrderEntry_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Заказ.
        /// </summary>
        internal static string OrderEntry_Order {
            get {
                return ResourceManager.GetString("OrderEntry_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Исполнитель.
        /// </summary>
        internal static string OrderEntry_Person {
            get {
                return ResourceManager.GetString("OrderEntry_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Регистрационный номер.
        /// </summary>
        internal static string OrderEntry_RegNum {
            get {
                return ResourceManager.GetString("OrderEntry_RegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дата принятия заказа.
        /// </summary>
        internal static string OrderEntry_StartTime {
            get {
                return ResourceManager.GetString("OrderEntry_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Статус заказа.
        /// </summary>
        internal static string OrderEntry_Status {
            get {
                return ResourceManager.GetString("OrderEntry_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Адрес.
        /// </summary>
        internal static string Order_Address {
            get {
                return ResourceManager.GetString("Order_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Заказчик.
        /// </summary>
        internal static string Order_Customer {
            get {
                return ResourceManager.GetString("Order_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как ФИО.
        /// </summary>
        internal static string Person_FIO {
            get {
                return ResourceManager.GetString("Person_FIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Название.
        /// </summary>
        internal static string Status_Name {
            get {
                return ResourceManager.GetString("Status_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Тип счётчика.
        /// </summary>
        internal static string Stavka_MeterType {
            get {
                return ResourceManager.GetString("Stavka_MeterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Исполнитель.
        /// </summary>
        internal static string Stavka_Person {
            get {
                return ResourceManager.GetString("Stavka_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Город.
        /// </summary>
        internal static string Street_City {
            get {
                return ResourceManager.GetString("Street_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Название.
        /// </summary>
        internal static string Street_Name {
            get {
                return ResourceManager.GetString("Street_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Логин.
        /// </summary>
        internal static string User_Login {
            get {
                return ResourceManager.GetString("User_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Пароль.
        /// </summary>
        internal static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Тип пользователя.
        /// </summary>
        internal static string User_UserType {
            get {
                return ResourceManager.GetString("User_UserType", resourceCulture);
            }
        }
    }
}
