//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Address
    {
        public Address()
        {
            this.Order = new HashSet<Order>();
        }
        
        public int Id { get; set; }

        [Display(Name ="Address_Flat",ResourceType =typeof(GlobalResources.SiteResources))]
        public int Flat { get; set; }
        [Display(Name = "Address_House", ResourceType = typeof(GlobalResources.SiteResources))]
        public virtual House House { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
