//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Company : Customer
    {
        [Display(Name = "Company_CompanyName", ResourceType = typeof(GlobalResources.SiteResources))]
        public string CompanyName { get; set; }
        [Display(Name = "Company_INN", ResourceType = typeof(GlobalResources.SiteResources))]
        public string INN { get; set; }
    }
}
