//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class House
    {
        public House()
        {
            this.Address = new HashSet<Address>();
        }
    
        public int Id { get; set; }
        [Display(Name = "House_Number", ResourceType = typeof(GlobalResources.SiteResources))]
        public string Number { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        [Display(Name = "House_Street", ResourceType = typeof(GlobalResources.SiteResources))]
        public virtual Street Street { get; set; }
    }
}
