//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterType
    {
        public MeterType()
        {
            this.Meter = new HashSet<Meter>();
            this.Stavka = new HashSet<Stavka>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Meter> Meter { get; set; }
        public virtual ICollection<Stavka> Stavka { get; set; }
    }
}
