//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Order> OrderSet { get; set; }
        public DbSet<User> UserSet { get; set; }
        public DbSet<Customer> CustomerSet { get; set; }
        public DbSet<Person> PersonSet { get; set; }
        public DbSet<Stavka> StavkaSet { get; set; }
        public DbSet<Meter> MeterSet { get; set; }
        public DbSet<OrderEntry> OrderEntrySet { get; set; }
        public DbSet<MeterType> MeterTypeSet { get; set; }
        public DbSet<Status> StatusSet { get; set; }
        public DbSet<City> CitySet { get; set; }
        public DbSet<Street> StreetSet { get; set; }
        public DbSet<House> HouseSet { get; set; }
        public DbSet<Address> AddressSet { get; set; }
        public DbSet<UserToCustomer> UserToCustomerSet { get; set; }
    }
}
