//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Stavka
    {
        public int Id { get; set; }
        [Display(Name = "Stavka_Person", ResourceType = typeof(GlobalResources.SiteResources))]
        public virtual Person Person { get; set; }
        [Display(Name = "Stavka_MeterType", ResourceType = typeof(GlobalResources.SiteResources))]
        public virtual MeterType MeterType { get; set; }
    }
}
