//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Street
    {
        public Street()
        {
            this.House = new HashSet<House>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Street_Name", ResourceType = typeof(GlobalResources.SiteResources))]
        public string Name { get; set; }
        [Display(Name = "Street_City", ResourceType = typeof(GlobalResources.SiteResources))]
        public virtual City City { get; set; }
        public virtual ICollection<House> House { get; set; }
    }
}
