//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserToCustomer
    {
        public int Id { get; set; }
        [Display(Name = "UserToCustomer_User", ResourceType = typeof(GlobalResources.SiteResources))]
        public virtual User User { get; set; }
        [Display(Name = "UserToCustomer_Customer", ResourceType = typeof(GlobalResources.SiteResources))]
        public virtual Customer Customer { get; set; }
    }
}
