//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.UtilityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HashedToken
    {
        public int Id { get; set; }
        public string Value { get; set; }
    
        public virtual TokenInfo TokenInfo { get; set; }
    }
}
