//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.UtilityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteUtilitiesContainer : DbContext
    {
        public SiteUtilitiesContainer()
            : base("name=SiteUtilitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Token> TokenSet { get; set; }
        public virtual DbSet<TokenInfo> TokenInfoSet { get; set; }
        public virtual DbSet<HashedToken> HashedTokenSet { get; set; }
    }
}
