//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPractics2.Models.UtilityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenInfo
    {
        public int Id { get; set; }
        public System.DateTime dateTime { get; set; }
        public string Salt { get; set; }
        public string Login { get; set; }
        public string Source { get; set; }
    
        public virtual Token Token { get; set; }
        public virtual HashedToken HashedToken { get; set; }
    }
}
